// app/terms/page.tsx
import Link from "next/link"
import { Dna } from "lucide-react"

export const metadata = {
  title: "Terms of Service — AI Scientist",
  description: "Terms of Service for AI Scientist Drug Discovery Platform",
}

const LAST_UPDATED = "April 6, 2026"
const COMPANY      = "AI Scientist"
const EMAIL        = "legal@aiscientist.in"
const WEBSITE      = "https://aiscientist.in"

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4">

      {/* Header */}
      <div className="flex items-center gap-3 mb-8">
        <div className="h-9 w-9 rounded-xl bg-blue-600 flex items-center justify-center">
          <Dna className="h-4 w-4 text-white" />
        </div>
        <div>
          <p className="text-sm font-bold text-gray-900">{COMPANY}</p>
          <p className="text-xs text-gray-400">Terms of Service</p>
        </div>
      </div>

      {/* Research disclaimer — most important */}
      <div className="bg-amber-50 border-l-4 border-amber-500 rounded-r-xl px-5 py-4 mb-8">
        <p className="text-sm font-bold text-amber-800 mb-1">
          ⚠️ Important Research Disclaimer
        </p>
        <p className="text-sm text-amber-700 leading-relaxed">
          AI Scientist is for <strong>exploratory research purposes only</strong>.
          Results generated by this platform are not intended for clinical diagnosis,
          treatment decisions, regulatory submissions, or any direct patient care.
          All outputs must be independently validated by qualified researchers and
          medical professionals before any application.
        </p>
      </div>

      <div className="prose prose-sm max-w-none">
        <h1 className="text-2xl font-black text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: {LAST_UPDATED}</p>

        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using {COMPANY} ("{WEBSITE}"), you agree to be bound by
            these Terms of Service. If you do not agree to these terms, you may not
            use the platform. These terms constitute a legally binding agreement
            between you and {COMPANY}.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            {COMPANY} is an AI-powered drug discovery research platform that provides:
          </p>
          <ul>
            <li>Biomedical hypothesis generation using publicly available scientific data</li>
            <li>Protein target analysis from OpenTargets database</li>
            <li>Drug-target interaction analysis using FDA FAERS and clinical trial data</li>
            <li>Research literature retrieval from PubMed and Semantic Scholar</li>
            <li>GO/NO-GO decision recommendations for research prioritization</li>
            <li>AI-generated research summaries via large language models</li>
          </ul>
          <p>
            The service is provided for exploratory research purposes only and does not
            constitute medical advice, clinical guidance, or regulatory consultation.
          </p>
        </Section>

        <Section title="3. Research Use Only — Critical Limitation">
          <p>
            <strong>YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT:</strong>
          </p>
          <ul>
            <li>
              All results, hypotheses, recommendations, and outputs from {COMPANY} are
              for <strong>exploratory research purposes only</strong>
            </li>
            <li>
              No output from this platform should be used to make clinical decisions,
              diagnose patients, prescribe treatments, or guide direct patient care
            </li>
            <li>
              All AI-generated content must be independently validated by qualified
              researchers, pharmacologists, and medical professionals
            </li>
            <li>
              The platform does not replace peer review, clinical trials, or regulatory
              approval processes
            </li>
            <li>
              {COMPANY} makes no representations about the accuracy, completeness,
              or fitness for purpose of any analysis results
            </li>
          </ul>
        </Section>

        <Section title="4. Eligibility">
          <p>
            You must be at least 18 years of age and have the legal capacity to enter
            into a binding contract to use this service. By using {COMPANY}, you
            represent that you meet these requirements. The platform is intended for
            use by researchers, scientists, pharmaceutical professionals, and
            academic institutions.
          </p>
        </Section>

        <Section title="5. User Accounts">
          <p>
            You are responsible for maintaining the confidentiality of your account
            credentials and for all activities that occur under your account. You agree to:
          </p>
          <ul>
            <li>Provide accurate and complete registration information</li>
            <li>Notify us immediately of any unauthorized use of your account</li>
            <li>Not share your account credentials with third parties</li>
            <li>Not create multiple accounts to circumvent usage limits</li>
          </ul>
        </Section>

        <Section title="6. Subscription Plans and Billing">
          <p>
            {COMPANY} offers both free and paid subscription plans. By subscribing
            to a paid plan:
          </p>
          <ul>
            <li>
              You authorize us to charge your payment method through Razorpay on a
              monthly recurring basis
            </li>
            <li>
              Subscription fees are non-refundable except as required by applicable law
            </li>
            <li>
              We reserve the right to modify pricing with 30 days advance notice
            </li>
            <li>
              Your subscription renews automatically unless cancelled before the
              renewal date
            </li>
            <li>
              GST at applicable rates will be charged on all transactions for
              Indian customers
            </li>
          </ul>
        </Section>

        <Section title="7. Acceptable Use">
          <p>You agree not to use {COMPANY} to:</p>
          <ul>
            <li>Violate any applicable laws, regulations, or third-party rights</li>
            <li>
              Attempt to reverse-engineer, scrape, or systematically extract data
              from the platform
            </li>
            <li>
              Misrepresent AI-generated outputs as peer-reviewed scientific findings
            </li>
            <li>
              Use outputs to mislead patients, healthcare providers, or regulatory
              authorities
            </li>
            <li>Share account access or API keys with unauthorized parties</li>
            <li>Attempt to circumvent usage limits or security measures</li>
          </ul>
        </Section>

        <Section title="8. Intellectual Property">
          <p>
            The {COMPANY} platform, including its software, algorithms, user interface,
            and branding, is owned by {COMPANY} and protected by applicable intellectual
            property laws. You retain ownership of data you input into the platform.
            AI-generated outputs may be used for your research purposes subject to
            these terms.
          </p>
          <p>
            The platform uses publicly available scientific databases including
            OpenTargets, FDA FAERS, PubMed, and Semantic Scholar. We do not claim
            ownership of any underlying scientific data from these sources.
          </p>
        </Section>

        <Section title="9. Disclaimer of Warranties">
          <p>
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES
            OF ANY KIND, EITHER EXPRESS OR IMPLIED. {COMPANY.toUpperCase()} EXPRESSLY
            DISCLAIMS ALL WARRANTIES INCLUDING BUT NOT LIMITED TO:
          </p>
          <ul>
            <li>Accuracy or completeness of any analysis or recommendation</li>
            <li>Fitness for a particular research purpose</li>
            <li>Uninterrupted or error-free service</li>
            <li>Results that will meet your research requirements</li>
          </ul>
        </Section>

        <Section title="10. Limitation of Liability">
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, {COMPANY.toUpperCase()}
            SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
            OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA,
            OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE.
          </p>
          <p>
            Our total liability to you for any claims arising from these terms or
            your use of the service shall not exceed the amount paid by you to
            {COMPANY} in the twelve months preceding the claim.
          </p>
        </Section>

        <Section title="11. Indemnification">
          <p>
            You agree to indemnify and hold harmless {COMPANY}, its officers,
            directors, employees, and agents from any claims, damages, losses,
            or expenses (including reasonable legal fees) arising from your use
            of the service, violation of these terms, or misuse of any research
            outputs.
          </p>
        </Section>

        <Section title="12. Termination">
          <p>
            Either party may terminate this agreement at any time. {COMPANY} reserves
            the right to suspend or terminate your account immediately for violation
            of these terms. Upon termination, your right to access the service ceases
            and your data may be deleted after 30 days.
          </p>
        </Section>

        <Section title="13. Governing Law">
          <p>
            These terms are governed by the laws of India. Any disputes arising
            from these terms shall be subject to the exclusive jurisdiction of
            the courts located in India. If you are accessing the service from
            outside India, you are responsible for compliance with local laws.
          </p>
        </Section>

        <Section title="14. Changes to Terms">
          <p>
            We reserve the right to modify these terms at any time. We will notify
            registered users of material changes via email at least 14 days before
            they take effect. Your continued use of the service after the effective
            date constitutes acceptance of the updated terms.
          </p>
        </Section>

        <Section title="15. Contact">
          <p>
            For questions about these Terms of Service, please contact us at:{" "}
            <a href={`mailto:${EMAIL}`} className="text-blue-600 hover:text-blue-800">
              {EMAIL}
            </a>
          </p>
        </Section>
      </div>

      {/* Footer nav */}
      <div className="mt-12 pt-6 border-t border-gray-100 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-4 text-sm text-gray-400">
          <Link href="/privacy" className="hover:text-gray-600">Privacy Policy</Link>
          <Link href="/"        className="hover:text-gray-600">← Back to App</Link>
        </div>
        <p className="text-xs text-gray-300">© {new Date().getFullYear()} {COMPANY}</p>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="text-base font-bold text-gray-900 mb-3 pb-2 border-b border-gray-100">
        {title}
      </h2>
      <div className="text-sm text-gray-600 leading-relaxed space-y-3">
        {children}
      </div>
    </div>
  )
}