// app/terms/page.tsx — Global Terms of Service
import Link from "next/link"
import { Dna } from "lucide-react"

export const metadata = {
  title: "Terms of Service — Causyn AI",
  description: "Terms of Service for Causyn AI Drug Discovery Platform",
}

const LAST_UPDATED = "April 12, 2026"
const COMPANY      = "Causyn AI"
const EMAIL        = "legal@causyn.ai"
const WEBSITE      = "https://causyn.ai"

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="text-base font-bold text-gray-900 mb-3 pb-2 border-b border-gray-100">{title}</h2>
      <div className="text-sm text-gray-600 leading-relaxed space-y-3">{children}</div>
    </div>
  )
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4">

      {/* Header */}
      <div className="flex items-center gap-3 mb-8">
        <div className="h-9 w-9 rounded-xl bg-blue-600 flex items-center justify-center">
          <Dna className="h-4 w-4 text-white" />
        </div>
        <div>
          <p className="text-sm font-bold text-gray-900">{COMPANY}</p>
          <p className="text-xs text-gray-400">Terms of Service</p>
        </div>
      </div>

      {/* Research disclaimer */}
      <div className="bg-amber-50 border-l-4 border-amber-500 rounded-r-xl px-5 py-4 mb-8">
        <p className="text-sm font-bold text-amber-800 mb-1">
          ⚠️ Important Research Disclaimer
        </p>
        <p className="text-sm text-amber-700 leading-relaxed">
          Causyn AI is for <strong>exploratory research purposes only</strong>.
          Results generated by this platform are not intended for clinical diagnosis,
          treatment decisions, regulatory submissions, or any direct patient care.
          All outputs must be independently validated by qualified researchers and
          medical professionals before any application.
        </p>
      </div>

      <div className="prose prose-sm max-w-none">
        <h1 className="text-2xl font-black text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: {LAST_UPDATED}</p>

        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using {COMPANY} ("{WEBSITE}"), you agree to be bound by
            these Terms of Service ("Terms"). If you do not agree to these Terms,
            do not use our platform.
          </p>
          <p>
            These Terms apply to all users worldwide, regardless of location.
            Additional terms may apply based on your jurisdiction.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            {COMPANY} provides an AI-powered drug discovery research platform that analyzes
            publicly available biomedical databases including OpenTargets, FDA FAERS,
            ClinicalTrials.gov, PubMed, AlphaFold, and Semantic Scholar to generate
            research hypotheses and decision intelligence for exploratory purposes.
          </p>
          <p>
            Our platform uses artificial intelligence (GPT-4o-mini) to generate hypotheses,
            executive summaries, and research insights. These are AI-generated outputs
            and must be treated as starting points for further investigation, not
            as definitive scientific conclusions.
          </p>
        </Section>

        <Section title="3. Research Use Only — Critical Limitation">
          <p>
            <strong>You expressly acknowledge and agree that:</strong>
          </p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>This platform is for exploratory research purposes ONLY</li>
            <li>Outputs are not validated scientific findings and require independent verification</li>
            <li>Results must NOT be used for clinical diagnosis or treatment decisions</li>
            <li>Results must NOT be used for regulatory submissions without independent validation</li>
            <li>Results must NOT be used for direct patient care in any form</li>
            <li>You are solely responsible for how you use the information provided</li>
          </ul>
          <p>
            Violation of these limitations may result in immediate termination of your account.
          </p>
        </Section>

        <Section title="4. Account Registration">
          <p>
            To use our platform, you must create an account with accurate, complete information.
            You are responsible for maintaining the confidentiality of your account credentials
            and for all activities that occur under your account.
          </p>
          <p>
            You must be at least 18 years of age to create an account. By registering,
            you represent that you are 18 or older.
          </p>
          <p>
            You agree to notify us immediately at {EMAIL} of any unauthorized use of
            your account or any other security breach.
          </p>
        </Section>

        <Section title="5. Subscription Plans & Payments">
          <p>
            We offer Free, Academic, Professional, and Enterprise plans. Paid plans are
            billed monthly or annually as selected. All prices are in USD unless otherwise stated.
          </p>
          <p>
            Payments are processed by Stripe, a PCI-DSS Level 1 certified payment processor.
            We do not store your complete payment information.
          </p>
          <p>
            <strong>Refunds:</strong> We offer a 14-day money-back guarantee on all paid plans.
            After 14 days, no refunds are provided except where required by applicable law.
            Contact {EMAIL} to request a refund within the eligible period.
          </p>
          <p>
            <strong>Cancellation:</strong> You may cancel your subscription at any time.
            Cancellation takes effect at the end of your current billing period.
            You retain access to paid features until the period ends.
          </p>
          <p>
            <strong>Price changes:</strong> We reserve the right to change subscription prices.
            We will provide at least 30 days notice before any price changes take effect.
          </p>
        </Section>

        <Section title="6. Acceptable Use Policy">
          <p>You agree NOT to use our platform to:</p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>Make clinical decisions or provide medical advice to patients</li>
            <li>Submit results to regulatory bodies without independent validation</li>
            <li>Reverse engineer, decompile, or attempt to extract our source code</li>
            <li>Scrape or systematically download data from our platform</li>
            <li>Use automated tools to abuse our API or exceed rate limits</li>
            <li>Share account credentials with unauthorized users</li>
            <li>Upload harmful, malicious, or illegal content</li>
            <li>Violate any applicable laws or regulations</li>
          </ul>
        </Section>

        <Section title="7. Intellectual Property">
          <p>
            All platform software, interfaces, logos, and proprietary algorithms are owned
            by {COMPANY} and protected by intellectual property laws worldwide.
          </p>
          <p>
            <strong>Your content:</strong> You retain ownership of disease names and research
            queries you submit. By using our platform, you grant us a limited license to
            process your inputs to provide the service.
          </p>
          <p>
            <strong>AI outputs:</strong> Research hypotheses, summaries, and analyses generated
            by our AI are provided for your use under a non-exclusive license.
            You may use them for legitimate research purposes with appropriate attribution.
          </p>
          <p>
            <strong>Third-party data:</strong> Our platform aggregates data from publicly available
            sources (OpenTargets, PubMed, FDA, etc.). This data is subject to their respective
            terms and licenses.
          </p>
        </Section>

        <Section title="8. Data & Privacy">
          <p>
            Your use of the platform is also governed by our{" "}
            <Link href="/privacy" className="text-blue-600 hover:text-blue-800">Privacy Policy</Link>,
            which is incorporated into these Terms by reference.
          </p>
          <p>
            We do not sell your personal data. We do not share your research queries
            or analysis results with third parties except as necessary to provide the service.
          </p>
        </Section>

        <Section title="9. Disclaimers & Limitation of Liability">
          <p>
            THE PLATFORM IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED.
            WE DO NOT WARRANT THAT THE PLATFORM WILL BE ERROR-FREE, UNINTERRUPTED, OR THAT
            THE RESULTS OBTAINED WILL BE ACCURATE OR RELIABLE.
          </p>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, {COMPANY.toUpperCase()} SHALL NOT
            BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
            INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR RELATED TO YOUR
            USE OF THE PLATFORM.
          </p>
          <p>
            OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM THESE TERMS OR YOUR USE
            OF THE PLATFORM SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS
            PRECEDING THE CLAIM.
          </p>
        </Section>

        <Section title="10. Indemnification">
          <p>
            You agree to indemnify and hold {COMPANY}, its officers, directors, employees,
            and agents harmless from any claims, damages, losses, or expenses (including
            reasonable legal fees) arising from your use of the platform, violation of
            these Terms, or violation of any third-party rights.
          </p>
        </Section>

        <Section title="11. Termination">
          <p>
            We may suspend or terminate your account at any time if you violate these Terms,
            with or without notice.
          </p>
          <p>
            You may terminate your account at any time by contacting {EMAIL}.
            Upon termination, your right to use the platform ceases immediately.
          </p>
          <p>
            Provisions that by their nature should survive termination (including disclaimers,
            limitations of liability, and dispute resolution) shall survive.
          </p>
        </Section>

        <Section title="12. Governing Law & Dispute Resolution">
          <p>
            These Terms are governed by and construed in accordance with the laws of the
            State of Delaware, United States, without regard to conflict of law principles.
          </p>
          <p>
            Any disputes arising from these Terms shall first be resolved through good-faith
            negotiation. If unresolved within 30 days, disputes shall be settled by binding
            arbitration in accordance with the rules of the American Arbitration Association.
          </p>
          <p>
            <strong>EU/UK users:</strong> Nothing in these Terms limits your rights under
            applicable EU or UK consumer protection laws.
          </p>
        </Section>

        <Section title="13. Changes to Terms">
          <p>
            We may update these Terms at any time. We will notify you of material changes
            by email or by displaying a notice on the platform at least 14 days before
            the changes take effect.
          </p>
          <p>
            Your continued use of the platform after changes take effect constitutes
            acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="14. Contact">
          <p>For legal questions or concerns, contact us at:</p>
          <div className="bg-gray-50 rounded-xl p-4 mt-2">
            <p><strong>Causyn AI — Legal Team</strong></p>
            <p>Email: <a href={`mailto:${EMAIL}`} className="text-blue-600">{EMAIL}</a></p>
            <p>Website: <a href={WEBSITE} className="text-blue-600">{WEBSITE}</a></p>
          </div>
        </Section>
      </div>

      {/* Footer links */}
      <div className="mt-10 pt-6 border-t border-gray-100 flex items-center justify-between">
        <Link href="/privacy" className="text-sm text-blue-600 hover:text-blue-800">Privacy Policy →</Link>
        <Link href="/"        className="text-sm text-gray-400 hover:text-gray-600">← Back to Dashboard</Link>
      </div>
    </div>
  )
}